# Generated by Django 5.1.3 on 2026-04-13 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("rate_per_unit", models.DecimalField(decimal_places=4, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "device",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UsageSession",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("total_cost", models.DecimalField(decimal_places=4, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "device_id",
                    models.ForeignKey(
                        db_column="device_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "db_table": "usagesession",
                "managed": True,
            },
        ),
    ]
