# Generated by Django 5.1.3 on 2026-04-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagesession",
            name="last_ping_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
